### ISSUE TITLE
Use ethers@6 for events polling

### ISSUE THREAD

**Issue by juliangruber** [filecoin-station/spark-evaluate#165]
Glif & Chain.love RPC nodes now support `eth_newFilter` and `eth_getFilterChanges`, so we should be able to use `ethers@6` without https://github.com/filecoin-station/on-contract-event

**Comment by bajtos** [comment]
FWIW, our experience in spark-api is that Lotus does not support filters when using JSON RPC, only when using web sockets.

However, it seems to be possible to configure Ethers v6 to use the old polling mechanism, see https://github.com/filecoin-station/spark-api/pull/306

**Comment by juliangruber** [comment]
We've already switched to ethers@6
