### ISSUE TITLE
Detect when TXs submitting evaluation scores are not added to the chain

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/spark-evaluate#314]
We should detect when transactions committing round evaluation scores are not added to the blockchain.

For example, when the gas base fee suddenly and significantly increases, our estimation of the required gas amount is too low, no miner accepts the message, and the message sits in the queue until the gas base fee goes down again. This has two problems:
- Because Filecoin maintains a strict order of messages from each address, subsequent transactions cannot be committed before the older pending transactions are committed first.
- If the gas base fee never goes below the level we need, our transactions will be stuck forever.

<img width="1324" alt="Screenshot 2024-08-09 at 12 06 18" src="https://github.com/user-attachments/assets/ed68adf6-a39c-4f57-9c0d-1c1cb5c31148">

The first step is to detect this situation and trigger an alert sent to our Slack channel, so that we are aware of the problem.

**Comment by juliangruber** [comment]
Alerts added 👍
