### ISSUE TITLE
Always round up evaluation to MAX_SCORE

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/spark-evaluate#49]
We are calculating individual participant scores as a fraction of the sum of honest jobs and then mapping this fraction to an integer in the `0..MAX_SCORE` range. When we sum up the final scores, we often get a slightly smaller value due to rounding errors.

For example:

```
EVALUTE ROUND 939: Invoking IE.setScores(); number of participants: 2, total score: 999999999999999n
```

The IE contract does not consider the round evaluation to be finished until the scores add up to MAX_SCORE. As a result, we end up with rounds with evaluations that have never finished.

To fix this, the evaluation service should add a rounding item to the scores, assigning the remainder to the burner address `0x000000000000000000000000000000000000dEaDz`.

The IE contract MUST recognise the burner address and ignore evaluation scores for this address when paying out rewards.

**Comment by juliangruber** [comment]
> The IE contract MUST recognise the burner address and ignore evaluation scores for this address when paying out rewards.

Just to confirm, this is implemented already
